# Generated by Django 3.1.7 on 2022-08-31 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_name', models.CharField(max_length=255)),
                ('bo_nit', models.IntegerField(default=0)),
                ('bo_address', models.TextField(blank=True)),
                ('bo_phone', models.CharField(max_length=255)),
                ('bo_email', models.CharField(max_length=255)),
                ('bo_create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branch Office',
                'verbose_name_plural': 'Branch Offices',
                'db_table': 'branch_office',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(max_length=255)),
                ('cl_dni', models.IntegerField(default=0)),
                ('cl_address', models.TextField(blank=True)),
                ('cl_phone', models.CharField(max_length=255)),
                ('cl_email', models.CharField(max_length=255)),
                ('cl_create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_name', models.CharField(max_length=255)),
                ('pd_description', models.TextField(blank=True)),
                ('pd_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pd_create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_date', models.DateTimeField(auto_now_add=True)),
                ('inv_quantity', models.IntegerField(default=0)),
                ('inv_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inv_create_at', models.DateTimeField(auto_now_add=True)),
                ('inv_branch_office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branchoffice')),
                ('inv_client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
                ('inv_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory',
            },
        ),
    ]
