# Generated by Django 3.1.7 on 2022-08-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='inv_branch_office_id',
            new_name='inv_branch_office',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='inv_client_id',
            new_name='inv_client',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='inv_product_id',
            new_name='inv_product',
        ),
    ]
